import type { NodeDefinition } from "@/lib/types/flow"

// TODO(post-MVP): fetch from GET /api/v1/flows/node-types — exported from Python Pydantic schemas
// For MVP, these definitions are maintained client-side and match Python BaseNode implementations

export const NODE_DEFINITIONS: NodeDefinition[] = [
  {
    type: "start",
    label: "Bắt đầu",
    description: "Điểm bắt đầu flow, nhận tin nhắn từ người dùng.",
    category: "io",
    icon: "Play",
    inputs: [
      {
        name: "flow_state_init",
        label: "Khởi tạo Flow State",
        type: "flow_state_init_editor",
        required: false,
        default: [],
        connectableHandle: false,
        description: "Khai báo biến mặc định cho flow state trước khi chạy.",
      },
    ],
    outputs: [
      { name: "message", label: "Tin nhắn", type: "string" },
      { name: "state", label: "Flow State", type: "object" },
    ],
  },
  {
    type: "llm",
    label: "VNPT LLM",
    description: "Sử dụng LLM để phân tích input và tạo phản hồi.",
    category: "agent",
    icon: "Sparkles",
    inputs: [
      {
        name: "messages",
        label: "Messages",
        type: "messages_array",
        required: true,
        default: [{ role: "user", content: "{{start.message}}" }],
        connectableHandle: false,
      },
      {
        name: "model",
        label: "Model",
        type: "select",
        required: true,
        default: "llm-medium-v4",
        options: [
          { label: "llm-small-v4", value: "llm-small-v4" },
          { label: "llm-medium-v4", value: "llm-medium-v4" },
          { label: "llm-medium-v5", value: "llm-medium-v5" },
        ],
        connectableHandle: false,
      },
      {
        name: "credential",
        label: "Credential VNPT",
        type: "credential",
        required: true,
        connectableHandle: false,
      },
      {
        name: "temperature",
        label: "Temperature",
        type: "number",
        default: 0.7,
        connectableHandle: false,
      },
      {
        name: "max_tokens",
        label: "Max Tokens",
        type: "number",
        default: 2048,
        connectableHandle: false,
      },
      {
        name: "memory",
        label: "Bật bộ nhớ hội thoại",
        type: "boolean",
        default: false,
        connectableHandle: false,
      },
      {
        name: "memory_window",
        label: "Cửa sổ bộ nhớ (tin nhắn)",
        type: "number",
        default: 5,
        connectableHandle: false,
        showWhen: { field: "memory", value: true },
      },
      {
        name: "input",
        label: "Input",
        type: "any",
        connectableHandle: true,
      },
    ],
    outputs: [
      { name: "output", label: "Kết quả", type: "string" },
    ],
  },
  {
    type: "knowledge_base",
    label: "Knowledge Base",
    description: "Truy xuất thông tin từ knowledge base.",
    category: "tool",
    icon: "Search",
    inputs: [
      {
        name: "kb_id",
        label: "Knowledge Base",
        type: "kb",
        required: true,
        connectableHandle: false,
      },
      {
        name: "query",
        label: "Query",
        type: "string",
        default: "{{start.message}}",
        connectableHandle: false,
      },
      {
        name: "top_k",
        label: "Top K",
        type: "number",
        default: 5,
        connectableHandle: false,
      },
      {
        name: "input",
        label: "Input",
        type: "any",
        connectableHandle: true,
      },
    ],
    outputs: [
      { name: "context", label: "Ngữ cảnh", type: "string" },
      { name: "sources", label: "Nguồn", type: "array" },
    ],
  },
  {
    type: "end",
    label: "Kết thúc",
    description: "Kết thúc flow và trả kết quả cho người dùng.",
    category: "io",
    icon: "Play",
    // Flow tự động kết thúc ở node lá (không có outgoing edge).
    // Giữ definition để các flow cũ vẫn render, nhưng ẩn khỏi palette.
    hiddenInPalette: true,
    inputs: [
      {
        name: "input",
        label: "Input",
        type: "any",
        connectableHandle: true,
      },
    ],
    outputs: [],
  },
  {
    type: "agent",
    label: "Agent",
    description: "Tự động chọn và sử dụng tools để thực hiện nhiều bước.",
    category: "agent",
    icon: "Bot",
    inputs: [
      {
        name: "tools",
        label: "Tools",
        type: "custom_tool_list",
        required: true,
        connectableHandle: false,
      },
      {
        name: "model",
        label: "Model",
        type: "select",
        required: true,
        default: "llm-medium-v4",
        options: [
          { label: "llm-small-v4", value: "llm-small-v4" },
          { label: "llm-medium-v4", value: "llm-medium-v4" },
          { label: "llm-medium-v5", value: "llm-medium-v5" },
        ],
        connectableHandle: false,
      },
      {
        name: "credential",
        label: "Credential VNPT",
        type: "credential",
        required: true,
        connectableHandle: false,
      },
      {
        name: "messages",
        label: "Messages",
        type: "messages_array",
        required: true,
        default: [
          { role: "system", content: "Bạn là trợ lý AI hữu ích." },
          { role: "user", content: "{{start.message}}" },
        ],
        connectableHandle: false,
      },
      {
        name: "memory_enabled",
        label: "Bật bộ nhớ",
        type: "boolean",
        default: false,
        connectableHandle: false,
      },
      {
        name: "memory_window",
        label: "Cửa sổ bộ nhớ (tin nhắn)",
        type: "number",
        default: 5,
        connectableHandle: false,
        showWhen: { field: "memory_enabled", value: true },
      },
      {
        name: "input",
        label: "Input",
        type: "any",
        connectableHandle: true,
      },
    ],
    outputs: [
      { name: "output", label: "Kết quả", type: "string" },
    ],
  },
  {
    type: "custom_tool",
    label: "Custom Tool",
    description: "Thực thi công cụ tùy chỉnh.",
    category: "tool",
    icon: "Wrench",
    inputs: [
      {
        name: "tool_id",
        label: "Tool",
        type: "custom_tool_list",
        required: true,
        connectableHandle: false,
      },
      {
        name: "input",
        label: "Input",
        type: "any",
        connectableHandle: true,
      },
    ],
    outputs: [
      { name: "output", label: "Kết quả", type: "any" },
    ],
  },
  {
    type: "code",
    label: "Code",
    description: "Thực thi code Python tùy chỉnh.",
    category: "tool",
    icon: "Code",
    inputs: [
      {
        name: "code",
        label: "Python Code",
        type: "code",
        required: true,
        default: "def run(state):\n    return {\"result\": state.get(\"message\", \"\")}",
        connectableHandle: false,
      },
      {
        name: "input",
        label: "Input",
        type: "any",
        connectableHandle: true,
      },
    ],
    outputs: [
      { name: "output", label: "Kết quả", type: "any" },
    ],
  },
  {
    type: "set_variable",
    label: "Set Variable",
    description: "Cập nhật biến trong Flow State.",
    category: "control",
    icon: "GitBranch",
    hiddenInPalette: true,
    inputs: [
      {
        name: "key",
        label: "Tên biến",
        type: "string",
        required: true,
        connectableHandle: false,
      },
      {
        name: "value",
        label: "Giá trị",
        type: "string",
        required: true,
        connectableHandle: false,
      },
      {
        name: "input",
        label: "Input",
        type: "any",
        connectableHandle: true,
      },
    ],
    outputs: [
      { name: "output", label: "Output", type: "any" },
    ],
  },
  {
    type: "text_formatter",
    label: "Text Formatter",
    description: "Định dạng và ghép nối văn bản theo template.",
    category: "tool",
    icon: "MessageSquare",
    inputs: [
      {
        name: "template",
        label: "Template",
        type: "string",
        required: true,
        default: "",
        connectableHandle: false,
      },
      {
        name: "input",
        label: "Input",
        type: "any",
        connectableHandle: true,
      },
    ],
    outputs: [
      { name: "output", label: "Kết quả", type: "string" },
    ],
  },
  {
    type: "memory",
    label: "Memory",
    description: "Quản lý bộ nhớ hội thoại (history).",
    category: "memory",
    icon: "MessageSquare",
    hiddenInPalette: true,
    inputs: [
      {
        name: "action",
        label: "Hành động",
        type: "select",
        required: true,
        default: "get",
        options: [
          { label: "Get", value: "get" },
          { label: "Set", value: "set" },
          { label: "Clear", value: "clear" },
        ],
        connectableHandle: false,
      },
      {
        name: "key",
        label: "Key",
        type: "string",
        required: false,
        default: "",
        connectableHandle: false,
      },
      {
        name: "value",
        label: "Value",
        type: "string",
        required: false,
        default: "",
        connectableHandle: false,
      },
      {
        name: "input",
        label: "Input",
        type: "any",
        connectableHandle: true,
      },
    ],
    outputs: [
      { name: "output", label: "Output", type: "any" },
    ],
  },
  {
    type: "condition",
    label: "Điều kiện",
    description: "Rẽ nhánh theo điều kiện If/Else.",
    category: "control",
    icon: "GitBranch",
    dynamicOutputs: "conditions",
    inputs: [
      {
        name: "conditions",
        label: "Điều kiện",
        type: "conditions_array",
        required: true,
        default: [],
        connectableHandle: false,
      },
      {
        name: "input",
        label: "Input",
        type: "any",
        connectableHandle: true,
      },
    ],
    outputs: [], // Dynamic — generated based on conditions count
  },
  {
    type: "smart_router",
    label: "Smart Router",
    description: "Sử dụng LLM để phân loại và điều hướng tự động.",
    category: "control",
    icon: "Brain",
    dynamicOutputs: "intents",
    inputs: [
      {
        name: "model",
        label: "Model",
        type: "select",
        required: true,
        default: "llm-small-v4",
        options: [
          { label: "llm-small-v4", value: "llm-small-v4" },
          { label: "llm-medium-v4", value: "llm-medium-v4" },
          { label: "llm-medium-v5", value: "llm-medium-v5" },
        ],
        connectableHandle: false,
      },
      {
        name: "credential",
        label: "Credential VNPT",
        type: "credential",
        required: true,
        connectableHandle: false,
      },
      {
        name: "instructions",
        label: "Hướng dẫn",
        type: "string",
        required: true,
        default: "Phân loại câu hỏi của người dùng",
        connectableHandle: false,
        description: "Hướng dẫn cho AI về cách phân loại input.",
      },
      {
        name: "input",
        label: "Input",
        type: "string",
        required: true,
        default: "{{start.message}}",
        connectableHandle: false,
        description: "Nội dung cần phân loại. Hỗ trợ {{variable}}.",
      },
      {
        name: "intents",
        label: "Intents",
        type: "intents_array",
        required: true,
        default: [],
        connectableHandle: false,
      },
    ],
    outputs: [], // Dynamic — generated based on intents count
  },
  {
    type: "http_request",
    label: "HTTP Request",
    description: "Gửi HTTP request đến API bên ngoài.",
    category: "tool",
    icon: "Globe",
    inputs: [
      {
        name: "url",
        label: "URL",
        type: "string",
        required: true,
        connectableHandle: false,
      },
      {
        name: "method",
        label: "Method",
        type: "select",
        default: "GET",
        options: [
          { label: "GET", value: "GET" },
          { label: "POST", value: "POST" },
          { label: "PUT", value: "PUT" },
          { label: "PATCH", value: "PATCH" },
          { label: "DELETE", value: "DELETE" },
        ],
        connectableHandle: false,
      },
      {
        name: "headers",
        label: "Headers (JSON)",
        type: "code",
        default: "{}",
        connectableHandle: false,
      },
      {
        name: "body",
        label: "Body (JSON)",
        type: "code",
        default: "{}",
        connectableHandle: false,
      },
      {
        name: "input",
        label: "Input",
        type: "any",
        connectableHandle: true,
      },
    ],
    outputs: [
      { name: "response", label: "Response", type: "any" },
      { name: "status", label: "Status Code", type: "number" },
    ],
  },
  {
    type: "human_input",
    label: "Human Input",
    description: "Yêu cầu input từ người dùng trong quá trình chạy.",
    category: "io",
    icon: "User",
    inputs: [
      {
        name: "prompt",
        label: "Câu hỏi cho người dùng",
        type: "string",
        required: true,
        connectableHandle: false,
      },
      {
        name: "input",
        label: "Input",
        type: "any",
        connectableHandle: true,
      },
    ],
    outputs: [
      { name: "response", label: "Phản hồi", type: "string" },
    ],
  },
  {
    type: "sticky_note",
    label: "Ghi chú",
    description: "Ghi chú không tham gia vào luồng thực thi.",
    category: "utility",
    icon: "StickyNote",
    hiddenInPalette: true,
    inputs: [
      {
        name: "content",
        label: "Nội dung",
        type: "string",
        default: "",
        connectableHandle: false,
      },
    ],
    outputs: [],
  },
]

export const NODE_DEFINITION_MAP: Record<string, NodeDefinition> = Object.fromEntries(
  NODE_DEFINITIONS.map((d) => [d.type, d])
)
