"""ConditionNode — evaluates conditions array, routes to first matching branch index."""
from typing import Any, Callable, Literal

from pydantic import BaseModel

from app.flow.base_node import BaseNode, NodeDefinition, NodeInput
from app.flow.context import NodeExecutionContext
from app.flow.exceptions import NodeExecutionError
from app.flow.node_types import NodeCategory
from app.flow.registry import NodeRegistry


class ConditionRule(BaseModel):
    """Single condition rule for evaluation."""
    type: Literal["string", "number", "boolean"]
    value1: str  # supports {{ var }} templates
    operation: str
    value2: str = ""


# Operations map: type -> operation -> lambda(a, b) -> bool
OPERATIONS: dict[str, dict[str, Callable[[Any, Any], bool]]] = {
    "string": {
        "equal": lambda a, b: str(a) == str(b),
        "not_equal": lambda a, b: str(a) != str(b),
        "contains": lambda a, b: str(b) in str(a),
        "starts_with": lambda a, b: str(a).startswith(str(b)),
        "ends_with": lambda a, b: str(a).endswith(str(b)),
        "is_empty": lambda a, _: not str(a).strip(),
        "is_not_empty": lambda a, _: bool(str(a).strip()),
    },
    "number": {
        "equal": lambda a, b: float(a) == float(b),
        "not_equal": lambda a, b: float(a) != float(b),
        "greater_than": lambda a, b: float(a) > float(b),
        "less_than": lambda a, b: float(a) < float(b),
        "gte": lambda a, b: float(a) >= float(b),
        "lte": lambda a, b: float(a) <= float(b),
    },
    "boolean": {
        "is_true": lambda a, _: _to_bool(a) is True,
        "is_false": lambda a, _: _to_bool(a) is False,
    },
}


def _to_bool(val: Any) -> bool:
    """Convert value to boolean, handling string 'true'/'false'."""
    if isinstance(val, bool):
        return val
    if isinstance(val, str):
        return val.lower() in ("true", "1", "yes")
    return bool(val)


@NodeRegistry.register
class ConditionNode(BaseNode):
    definition = NodeDefinition(
        type="condition",
        category=NodeCategory.CONTROL,
        label="Điều kiện",
        description="Rẽ nhánh flow dựa trên điều kiện. Đánh giá từng điều kiện theo thứ tự, route đến branch đầu tiên khớp.",
        icon="git-branch",
        inputs=[
            NodeInput(
                name="conditions",
                type="conditions_array",
                required=True,
                default=[],
            ),
        ],
        outputs=[],  # Dynamic — generated by frontend based on conditions count
    )

    async def execute(self, ctx: NodeExecutionContext) -> dict[str, Any]:
        conditions_raw = ctx.inputs.get("conditions", [])

        if not conditions_raw:
            raise NodeExecutionError("Condition node requires at least 1 condition")

        # Parse conditions
        conditions: list[ConditionRule] = []
        for i, cond in enumerate(conditions_raw):
            try:
                conditions.append(ConditionRule(**cond))
            except Exception as e:
                raise NodeExecutionError(f"Invalid condition at index {i}: {e}") from e

        # Evaluate conditions in order, return first match
        for i, cond in enumerate(conditions):
            try:
                # Resolve templates in value1 and value2
                val1 = ctx.resolve(cond.value1)
                val2 = ctx.resolve(cond.value2)

                # Get operation function
                type_ops = OPERATIONS.get(cond.type)
                if not type_ops:
                    raise NodeExecutionError(f"Unknown condition type: {cond.type}")

                op_func = type_ops.get(cond.operation)
                if not op_func:
                    raise NodeExecutionError(
                        f"Unknown operation '{cond.operation}' for type '{cond.type}'"
                    )

                # Evaluate
                result = op_func(val1, val2)
                if result:
                    return {"branch": str(i), "matched_index": i, "matched_value": val1}

            except NodeExecutionError:
                raise
            except ValueError as e:
                # Type coercion error (e.g., invalid float)
                raise NodeExecutionError(
                    f"Condition {i} type error: {e}. value1='{cond.value1}', value2='{cond.value2}'"
                ) from e
            except Exception as e:
                raise NodeExecutionError(f"Condition {i} evaluation error: {e}") from e

        # No condition matched
        raise NodeExecutionError(
            f"No condition matched. Evaluated {len(conditions)} conditions."
        )
