"""SmartRouterNode — LLM-driven routing based on intent matching."""
from __future__ import annotations

import re
from typing import Any

from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage
from pydantic import BaseModel

from app.flow.base_node import BaseNode, NodeDefinition, NodeInput
from app.flow.context import NodeExecutionContext
from app.flow.exceptions import NodeExecutionError
from app.flow.node_types import NodeCategory
from app.flow.registry import NodeRegistry

_VNPT_BASE_URL = "https://assistant-stream.vnpt.vn/v1/"
_DEFAULT_MODEL = "llm-small-v4"


class Intent(BaseModel):
    """Single intent for LLM classification."""
    description: str


_ROUTING_PROMPT = """You are a routing agent. Based on the instructions and user input, determine which intent best matches.

Instructions: {instructions}

Available intents:
{intents_list}

User input: {input}

Respond with ONLY the intent number (0, 1, 2, etc.) that best matches. No explanation, just the number."""


def _resolve_credential(credentials: dict[str, dict], credential_id: str) -> dict[str, str]:
    """Resolve LLM credential. Falls back to engine env vars when no credential_id provided."""
    from app.config import settings

    cred = credentials.get(credential_id) if credential_id else None
    if not cred:
        env_key = settings.LLM_API_KEY
        env_url = settings.LLM_BASE_URL
        if env_key:
            return {"api_key": env_key, "base_url": env_url or _VNPT_BASE_URL, "model": ""}
        if credential_id:
            raise NodeExecutionError(f"SmartRouterNode: credential '{credential_id}' not found")
        raise NodeExecutionError("SmartRouterNode: no credential configured and LLM_API_KEY env var not set")

    normalized: dict[str, str] = {
        "api_key": cred.get("api_key") or cred.get("apiKey") or "",
        "base_url": cred.get("base_url") or cred.get("baseUrl") or "",
        "model": cred.get("model") or "",
    }
    if not normalized["api_key"]:
        raise NodeExecutionError(f"SmartRouterNode: credential '{credential_id}' missing required 'api_key'")
    return normalized


def _parse_intent_index(response: str, max_index: int) -> int:
    """Parse LLM response to extract intent index."""
    text = response.strip()

    match = re.search(r"\d+", text)
    if not match:
        raise NodeExecutionError(
            f"SmartRouterNode: LLM returned invalid response '{text}'. Expected a number."
        )

    index = int(match.group())
    if index < 0 or index > max_index:
        raise NodeExecutionError(
            f"SmartRouterNode: LLM returned index {index} out of range [0, {max_index}]"
        )

    return index


@NodeRegistry.register
class SmartRouterNode(BaseNode):
    definition = NodeDefinition(
        type="smart_router",
        category=NodeCategory.CONTROL,
        label="Smart Router",
        description="LLM phân loại input và route đến nhánh phù hợp nhất.",
        icon="brain",
        inputs=[
            NodeInput(name="model", type="string", required=False, default=_DEFAULT_MODEL),
            NodeInput(name="credential", type="string", required=True),
            NodeInput(name="instructions", type="string", required=True, default="Classify the user input"),
            NodeInput(name="input", type="string", required=True, default="{{start.message}}"),
            NodeInput(name="intents", type="intents_array", required=True, default=[]),
        ],
        outputs=[],  # Dynamic — generated by frontend based on intents count
    )

    async def execute(self, ctx: NodeExecutionContext) -> dict[str, Any]:
        credential_id = ctx.resolve(ctx.inputs.get("credential", ""))
        cred = _resolve_credential(ctx.credentials, credential_id)

        model = ctx.resolve(ctx.inputs.get("model", "")) or cred["model"] or _DEFAULT_MODEL
        base_url = cred["base_url"] or _VNPT_BASE_URL

        intents_raw = ctx.inputs.get("intents", [])
        if not intents_raw:
            raise NodeExecutionError("SmartRouterNode requires at least 1 intent")

        intents: list[Intent] = []
        for i, item in enumerate(intents_raw):
            try:
                intents.append(Intent(**item))
            except Exception as e:
                raise NodeExecutionError(f"Invalid intent at index {i}: {e}") from e

        intents_list = "\n".join(
            f"{i}: {intent.description}" for i, intent in enumerate(intents)
        )

        instructions = ctx.resolve(ctx.inputs.get("instructions", ""))
        user_input = ctx.resolve(ctx.inputs.get("input", ""))

        prompt = _ROUTING_PROMPT.format(
            instructions=instructions,
            intents_list=intents_list,
            input=user_input,
        )

        llm = ChatOpenAI(
            api_key=cred["api_key"],
            base_url=base_url,
            model=model,
            temperature=0.0,
            max_tokens=10,
        )

        messages = [
            SystemMessage(content="You are a precise routing agent. Output only numbers."),
            HumanMessage(content=prompt),
        ]

        try:
            response = await llm.ainvoke(messages)
            response_text = response.content or ""
        except Exception as e:
            raise NodeExecutionError(f"SmartRouterNode LLM call failed: {e}") from e

        max_index = len(intents) - 1
        index = _parse_intent_index(response_text, max_index)

        return {
            "branch": str(index),
            "matched_index": index,
            "matched_intent": intents[index].description,
            "llm_response": response_text,
        }
